export const PHOTO_DATA = {
  angari: [
    { id: "1", src: "/photo/angari/1.jpg" },
    { id: "2", src: "/photo/angari/2.jpg" },
    { id: "3", src: "/photo/angari/3.jpg" },
    { id: "4", src: "/photo/angari/4.jpg" },
    { id: "5", src: "/photo/angari/5.jpg" },
    { id: "6", src: "/photo/angari/6.jpg" },
    { id: "7", src: "/photo/angari/7.jpg" },
    { id: "8", src: "/photo/angari/8.jpg" },
    { id: "9", src: "/photo/angari/9.jpg" },
  ],
  basseini: [{ id: "", src: "" }],
  "burovie-ukritya": [{ id: "", src: "" }],
  furi: [{ id: "", src: "" }],
  krovlya: [{ id: "", src: "" }],
  laguni: [{ id: "", src: "" }],
  "myagkie-okna": [{ id: "", src: "" }],
  paviloni: [{ id: "", src: "" }],
  pricepi: [{ id: "", src: "" }],
  "selhoz-ukritya": [{ id: "", src: "" }],
};
