export const PHOTO_DATA = {
  angari: {
    name: "Ангары",
    data: [
      { id: "1", src: "/photo/angari/1.jpg" },
      { id: "2", src: "/photo/angari/2.jpg" },
      { id: "3", src: "/photo/angari/3.jpg" },
      { id: "4", src: "/photo/angari/4.jpg" },
      { id: "5", src: "/photo/angari/5.jpg" },
      { id: "6", src: "/photo/angari/6.jpg" },
      { id: "7", src: "/photo/angari/7.jpg" },
      { id: "8", src: "/photo/angari/8.jpg" },
      { id: "9", src: "/photo/angari/9.jpg" },
    ],
  },
  basseini: {
    name: "Бассейны",
    data: [
      { id: "1", src: "/photo/basseini/1.jpg" },
      { id: "2", src: "/photo/basseini/2.jpg" },
      { id: "3", src: "/photo/basseini/3.jpg" },
      { id: "4", src: "/photo/basseini/4.jpg" },
      { id: "5", src: "/photo/basseini/5.jpg" },
      { id: "6", src: "/photo/basseini/6.jpg" },
      { id: "7", src: "/photo/basseini/7.jpg" },
    ],
  },
  "burovie-ukritya": {
    name: "Буровые укрытия",
    data: [
      { id: "1", src: "/photo/burovie-ukritya/1.jpg" },
      { id: "2", src: "/photo/burovie-ukritya/2.jpg" },
      { id: "3", src: "/photo/burovie-ukritya/3.jpg" },
      { id: "4", src: "/photo/burovie-ukritya/4.jpg" },
      { id: "5", src: "/photo/burovie-ukritya/5.jpg" },
      { id: "6", src: "/photo/burovie-ukritya/6.jpg" },
      { id: "7", src: "/photo/burovie-ukritya/7.jpg" },
      { id: "8", src: "/photo/burovie-ukritya/8.jpg" },
      { id: "9", src: "/photo/burovie-ukritya/9.jpg" },
    ],
  },
  furi: {
    name: "Тенты на фуры",
    data: [
      { id: "1", src: "/photo/furi/1.jpg" },
      { id: "2", src: "/photo/furi/2.jpg" },
      { id: "3", src: "/photo/furi/3.jpg" },
      { id: "4", src: "/photo/furi/4.jpg" },
      { id: "5", src: "/photo/furi/5.jpg" },
    ],
  },
  krovlya: {
    name: "Кровля",
    data: [
      { id: "1", src: "/photo/krovlya/1.jpg" },
      { id: "2", src: "/photo/krovlya/2.jpg" },
      { id: "3", src: "/photo/krovlya/3.jpg" },
      { id: "4", src: "/photo/krovlya/4.jpg" },
      { id: "5", src: "/photo/krovlya/5.jpg" },
      { id: "6", src: "/photo/krovlya/6.jpg" },
      { id: "7", src: "/photo/krovlya/7.jpg" },
    ],
  },
  laguni: {
    name: "Лагуны",
    data: [
      { id: "1", src: "/photo/laguni/1.jpg" },
      { id: "2", src: "/photo/laguni/2.jpg" },
      { id: "3", src: "/photo/laguni/3.jpg" },
      { id: "4", src: "/photo/laguni/4.jpg" },
      { id: "5", src: "/photo/laguni/5.jpg" },
      { id: "6", src: "/photo/laguni/6.jpg" },
      { id: "7", src: "/photo/laguni/7.jpg" },
      { id: "8", src: "/photo/laguni/8.jpg" },
      { id: "9", src: "/photo/laguni/9.jpg" },
      { id: "10", src: "/photo/laguni/10.jpg" },
      { id: "11", src: "/photo/laguni/11.jpg" },
      { id: "12", src: "/photo/laguni/12.jpg" },
      { id: "13", src: "/photo/laguni/13.jpg" },
      { id: "14", src: "/photo/laguni/14.jpg" },
    ],
  },
  "myagkie-okna": {
    name: "Мягкие окна",
    data: [{ id: "", src: "" }],
  },
  paviloni: {
    name: "Павильоны",
    data: [{ id: "", src: "" }],
  },
  pricepi: {
    name: "Тенты на прицепы",
    data: [{ id: "", src: "" }],
  },
  "selhoz-ukritya": {
    name: "Сельхозукрытия",
    data: [{ id: "", src: "" }],
  },
};
